#!/usr/bin/env python

import sys

docfor=""

if len(sys.argv)>=2 :
    print "Making documentation for "+sys.argv[1]
    docfor = "_for_"+sys.argv[1].split(".")[0].replace("/","_")
    execfile(sys.argv[1])
else :
    from textadv.basicsetup import *

sys.stdout = open("doc/doc"+docfor+".html", "w")

html_escape_table = {
    "&": "&amp;",
    '"': "&quot;",
    "'": "&apos;",
    ">": "&gt;",
    "<": "&lt;",
    }

def html_escape(text):
    """Produce entities within text."""
    if text :
        return "".join(html_escape_table.get(c,c) for c in text)
    else :
        return None

print "<html><body><h1>TextAdv auto-documentation</h1>"
print "<p>This is automagically generated documentation of the rules defined in the game engine.</p>"
world.make_documentation(html_escape, heading_level=1)
parser.make_documentation(html_escape, heading_level=1)
actionsystem.make_documentation(html_escape, heading_level=1)
actoractivities.make_documentation(html_escape, heading_level=1)

print "</body></html>"
